"use client";

import MatchTablePreview from "./MatchTablePreview";
import MathHtmlRenderer from "./MathHtmlRenderer";

const OPTION_KEYS = ["A", "B", "C", "D"];

function Badge({ children, tone = "neutral" }) {
  const tones = {
    neutral: "bg-neutral-100 text-neutral-700 border-neutral-200",
    easy: "bg-emerald-50 text-emerald-800 border-emerald-200",
    medium: "bg-amber-50 text-amber-800 border-amber-200",
    hard: "bg-rose-50 text-rose-800 border-rose-200",
    id: "bg-indigo-50 text-indigo-800 border-indigo-200",
  };
  return (
    <span
      className={`inline-flex items-center rounded-md border px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide ${
        tones[tone] || tones.neutral
      }`}
    >
      {children}
    </span>
  );
}

function difficultyTone(d) {
  if (d === "easy") return "easy";
  if (d === "hard") return "hard";
  return "medium";
}

function isGeneratedByTracker(year) {
  return String(year || "").toLowerCase() === "generated by 10tracker";
}

export default function McqCard({ mcq, index, editable = false, onChange }) {
  if (!mcq) return null;

  const update = (field, value) => {
    if (!onChange) return;
    onChange({ ...mcq, [field]: value });
  };

  return (
    <article className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm sm:p-5">
      <header className="mb-3 flex flex-wrap items-center gap-2">
        <Badge tone="id">{mcq._id || `#${index + 1}`}</Badge>
        {mcq.difficulty && (
          <Badge tone={difficultyTone(mcq.difficulty)}>{mcq.difficulty}</Badge>
        )}
        {isGeneratedByTracker(mcq.year) ? (
          <Badge tone="easy">Generated by 10Tracker</Badge>
        ) : (
          mcq.year && <Badge>{mcq.year}</Badge>
        )}
        {mcq.topic && <Badge>{mcq.topic}</Badge>}
      </header>

      {editable ? (
        <label className="mb-4 block text-sm">
          <span className="mb-1 block text-xs font-medium uppercase text-neutral-500">
            Question
          </span>
          <textarea
            rows={3}
            value={mcq.question || ""}
            onChange={(e) => update("question", e.target.value)}
            className="w-full rounded-xl border border-neutral-200 px-3 py-2 text-sm font-medium text-neutral-900 focus:border-neutral-400 focus:outline-none"
          />
        </label>
      ) : (
        <div className="mb-4 text-sm font-medium leading-relaxed text-neutral-900">
          <MathHtmlRenderer html={mcq.question} />
        </div>
      )}

      <MatchTablePreview directionHTML={mcq.directionHTML} />

      <ul className="space-y-2">
        {OPTION_KEYS.map((letter) => {
          const field = `options_${letter}`;
          const text = mcq[field];
          const isCorrect = mcq.correct_option === letter;
          return (
            <li
              key={letter}
              className={`rounded-xl border px-3 py-2.5 text-sm ${
                isCorrect
                  ? "border-emerald-300 bg-emerald-50 text-emerald-950"
                  : "border-neutral-200 bg-neutral-50 text-neutral-800"
              }`}
            >
              <div className="flex gap-2">
                <span
                  className={`shrink-0 font-semibold ${
                    isCorrect ? "text-emerald-700" : "text-neutral-500"
                  }`}
                >
                  {letter}.
                </span>
                {editable ? (
                  <textarea
                    rows={2}
                    value={text || ""}
                    onChange={(e) => update(field, e.target.value)}
                    className="min-w-0 flex-1 rounded-lg border border-neutral-200 bg-white px-2 py-1 text-sm focus:border-neutral-400 focus:outline-none"
                  />
                ) : (
                  <div className="min-w-0 flex-1">
                    <MathHtmlRenderer html={text} />
                  </div>
                )}
              </div>
            </li>
          );
        })}
      </ul>

      {editable && (
        <label className="mt-3 block text-sm">
          <span className="mb-1 block text-xs font-medium uppercase text-neutral-500">
            Correct option
          </span>
          <select
            value={mcq.correct_option || "A"}
            onChange={(e) => update("correct_option", e.target.value)}
            className="rounded-lg border border-neutral-200 px-3 py-1.5 text-sm"
          >
            {OPTION_KEYS.map((k) => (
              <option key={k} value={k}>
                {k}
              </option>
            ))}
          </select>
        </label>
      )}

      <section className="mt-4 rounded-xl border border-neutral-100 bg-neutral-50 p-3">
        <p className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-neutral-500">
          Solution
        </p>
        {editable ? (
          <textarea
            rows={4}
            value={mcq.solution || ""}
            onChange={(e) => update("solution", e.target.value)}
            className="w-full rounded-lg border border-neutral-200 bg-white px-3 py-2 text-sm text-neutral-700 focus:border-neutral-400 focus:outline-none"
          />
        ) : (
          <div className="text-sm leading-relaxed text-neutral-700">
            <MathHtmlRenderer html={mcq.solution} />
          </div>
        )}
      </section>
    </article>
  );
}
